name: Release Binaries

on:
  release:
    types:
      - released

jobs:
  build-desktop:
    name: Build for Desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, windows-latest]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk
          cache: 'gradle'

      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Increase version code
        run: python ./scripts/increaseVersionCode.py

      - name: Commit modified version code file
        id: commit_version_code
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'Updated Version'
          file_pattern: 'version.properties'
          branch: master

      - name: Build
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS

      - name: Rename deb
        if: startsWith(matrix.os, 'ubuntu')
        run: mv composeApp/build/compose/binaries/main-release/deb/*.deb composeApp/build/compose/binaries/main-release/deb/escalar-alcoia-i-comtat_${{ matrix.os }}_amd64.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/main-release/**/*.dmg
            composeApp/build/compose/binaries/main-release/**/*.exe
            composeApp/build/compose/binaries/main-release/**/*.deb
